-- 1. Create 'address' table (no dependencies)
CREATE TABLE address (
                         id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         street VARCHAR(255),
                         city VARCHAR(255),
                         state VARCHAR(255),
                         zip VARCHAR(255),
                         country VARCHAR(255),
                         phone VARCHAR(255),
                         email VARCHAR(255),
                         fax VARCHAR(255),
                         latitude DOUBLE PRECISION,
                         longitude DOUBLE PRECISION,
                         geohash VARCHAR(255)
);

-- 2. Create 'movie' table (no dependencies)
CREATE TABLE movie (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       title VARCHAR(255),
                       language VARCHAR(255),
                       genre VARCHAR(255),
                       duration_min INT,
                       rating VARCHAR(255)
);

-- 3. Create 'theater' table (depends on 'address')
CREATE TABLE theater (
                         id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         address_id BIGINT,
                         CONSTRAINT fk_theater_address FOREIGN KEY (address_id) REFERENCES address(id)
);

-- 4. Create 'show' table (depends on 'movie' and 'theater')
CREATE TABLE show (
                      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      title VARCHAR(255),
                      theater_name VARCHAR(255),
                      screen VARCHAR(255),
                      show_time TIMESTAMP WITH TIME ZONE,
                      ticket_price INT,
                      movie_id BIGINT,
                      theater_id BIGINT,
                      CONSTRAINT fk_show_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
                      CONSTRAINT fk_show_theater FOREIGN KEY (theater_id) REFERENCES theater(id)
);

-- Outbox events table - the key to reliable event publishing
CREATE TABLE movie_outbox_events (
                               id UUID PRIMARY KEY,
                               aggregate_type VARCHAR(255) NOT NULL,
                               type VARCHAR(255) NOT NULL,
                               payload JSONB NOT NULL,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);