### POST request listing-service hotel
POST http://localhost:4000/api/admin/hotel
Content-Type: application/json

{
  "name": "Magnus Classen",
  "description": "Near Sugondha",
  "rating": 3,
  "roomTypes": [{
    "roomType": "single",
    "totalRooms": 10,
    "pricePerNight": 100,
    "updatedAt": "2020-02-20T12:00:05Z",
    "ref": "room12"
  }, {
    "roomType": "double",
    "totalRooms": 10,
    "pricePerNight": 200,
    "updatedAt": "2028-02-20T12:00:05Z",
    "ref": "room18"
  }, {
    "roomType": "deluxe",
    "totalRooms": 10,
    "pricePerNight": 100,
    "updatedAt": "2021-02-20T12:00:05Z",
    "ref": "room13"
  }, {
    "roomType": "honeymoon",
    "totalRooms": 10,
    "pricePerNight": 100,
    "updatedAt": "2021-02-20T12:00:05Z",
    "ref": "room163"
  }],
  "updatedAt": "2028-02-20T12:00:05Z",
  "ref": "clas",
  "supplierRef": "supp1"
}

###